#!/bin/bash

# HapMapMix confident regions are an intersection of sample-specific confident regions from GIAB HG002, HG005 and the other four non-GIAB samples HG00438, HG02622, HG02257, HG02486.

# GIAB confident regions can be acquired from its FTP site.
# https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/
# https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG005_NA24631_son/

# Non-GIAB confident regions were generated by dipcall and can be acquired from HPRC
# https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC/HG00438/
# https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC/HG02622/
# https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC/HG02257/
# https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC/HG02486/

wget https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed
wget https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG005_NA24631_son/latest/GRCh38/HG005_GRCh38_1_22_v4.2.1_benchmark.bed
wget https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC/HG00438/assemblies/year1_f1_assembly_v2_genbank/assembly_qc/dipcall/HG00438.f1_assembly_v2_genbank.dip.bed
wget https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC/HG02622/assemblies/year1_f1_assembly_v2_genbank/assembly_qc/dipcall/HG02622.f1_assembly_v2_genbank.dip.bed
wget https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC/HG02257/assemblies/year1_f1_assembly_v2_genbank/assembly_qc/dipcall/HG02257.f1_assembly_v2_genbank.dip.bed
wget https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC/HG02486/assemblies/year1_f1_assembly_v2_genbank/assembly_qc/dipcall/HG02486.f1_assembly_v2_genbank.dip.bed

