ref_fa: "/n/data1/hms/dbmi/park-smaht_dac/ref/GRCh38_no_alt/hg38_no_alt.fa"
scripts: /n/data1/hms/dbmi/park/jiny/SMaHT/COLO829/2.Github/3.negative_control

pacbio:
  tumor_bam: "/n/data1/hms/dbmi/park-smaht_dac/analysis/GCC_UW/COLO829T/pacbioHifi_bulkFiberSeq/seq_data/COLO829T_Hifi_ReplacedRG.bam"
  normal_bam: "/n/data1/hms/dbmi/park/dominika/testing/smaht/negative_control/WGS/PacBio/COLO829BL/multiple_rg_2/COLO829_ReplacedreadGroups.bam"

illumina:
  tumor_bam: /n/data1/hms/dbmi/park/jiny/SMaHT/COLO829/TruthSet/input/merge_three_bams/COLO829T_Ill_200X.bam
  normal_bam: /n/data1/hms/dbmi/park/jiny/SMaHT/COLO829/TruthSet/input/merge_three_bams/COLO829BL_Ill_230X.bam 

beds:
  # BED1 is precomputed per job_id (you already have these)
  homref_candidates: /n/scratch/users/d/dm334/refHomCandidates/COLO829BL_T_region_homref_cand_{job_id}.bed

  # BED2 and BED3 are FIXED absolute paths produced by step 3 and 4:
  for_step2: "NegativeControlSet/intermediate/ForStep2_{job_id}.bed"
  to_check_in_illumina: "NegativeControlSet/intermediate/Step2_PacBio_PU30_ToCheckinIllumina/Step2_ToCheckInIllumina_{job_id}.bed"

# Optional job range
start: 0
end: 605
