from pathlib import Path

short_read_target_bam = config["short_read_target_bam"]
short_read_control_bam  = config["short_read_control_bam"]
variant_calls = config["variant_calls"]
reference_genome = config["reference_genome"]
output_pileup = variant_calls.replace(".vcf","").replace(".gz", "") 
output_final = config["output_vcf"]

script_path = Path(workflow.basedir).parent / "scripts"

rule all:
    input:
        output_final

rule pileup:
    input:
        short_read_control_bam = short_read_control_bam,
        short_read_target_bam = short_read_target_bam,
        variant_calls = variant_calls,
        reference = reference_genome
    output:
        output_pileup_vcf_norm = output_pileup + "_PU_norm.q20.Q20.vcf.gz"
    threads: 20
    resources:
        mem_mb = 8000,
        runtime = 1800
    params:
        chunk_size = 1000,
        tmpdir = f"{output_final}_tmp_target_sr_chunks",
        rawdir = f"{output_final}_tmp_target_sr_raw_vcfs",
        normdir = f"{output_final}_tmp_target_sr_norm_vcfs"
    shell:
        """
        
        rm -rf {params.tmpdir} {params.rawdir} {params.normdir}
        mkdir -p {params.tmpdir} {params.rawdir} {params.normdir}

        # Step 1: Convert VCF to 0-based BED
        bcftools query -f'%CHROM\\t%POS\\t%POS\\n' {input.variant_calls} | \
            awk -v OFS='\\t' '{{print $1, $2 - 1, $3}}' > {params.tmpdir}/regions.bed

        # Step 2: Split BED into chunks
        split -l {params.chunk_size} --additional-suffix=.bed {params.tmpdir}/regions.bed {params.tmpdir}/chunk_

        # Step 3: Parallel pileup + normalization
        ls {params.tmpdir}/chunk_*.bed | parallel --tmpdir {output_path} -j {threads} '
            chunk={{}};
            name=$(basename $chunk);
            raw={params.rawdir}/$name.vcf;
            norm={params.normdir}/$name.norm.vcf.gz;

            bcftools mpileup -f {input.reference} \
                --threads 1 \
                {input.short_read_control_bam} {input.short_read_target_bam} \
                --ignore-RG \
                -R $chunk \
                -a DP,AD \
                -d 3000 \
                --skip-any-set SECONDARY,DUP \
                -Q 20 -q 20 \
                > $raw;

            bcftools norm -m- -f {input.reference} $raw -O z -o $norm;
            tabix $norm;
        '

        # Step 4: Concatenate normalized chunks
        bcftools concat -a -O z -o {output.output_pileup_vcf_norm} {params.normdir}/*.norm.vcf.gz
        tabix {output.output_pileup_vcf_norm}
        """

rule filter:
    input:
        pileup_vcf_norm = output_pileup + "_PU_norm.q20.Q20.vcf.gz",
        short_read_target_bam = short_read_target_bam,
        short_read_control_bam = short_read_control_bam,
        input_vcf_calls = variant_calls
    output:
        output_vcf_calls = output_final
        
    threads: 1
    resources:
        mem_mb = 8000,
        runtime = 1800
    shell:
        """
        python3 {script_path}/filter_calls.py \
        --input_vcf_pu {input.pileup_vcf_norm} \
        --target_bam {input.short_read_target_bam} \
        --control_bam {input.short_read_control_bam} \
        --input_vcf_calls {input.input_vcf_calls} \
        --output_vcf_calls {output.output_vcf_calls}
        """
